name: app_tontine_bf
description: "Crafted by zoldyck."
publish_to: 'All_fams'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.2
  http: ^1.1.0
  cupertino_icons: ^1.0.8
  cloud_firestore: ^4.17.5
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"

# CORRECTION : Même nom que le fichier
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"  # ← logo.png comme ton fichier

flutter:
  uses-material-design: true

  # CORRECTION : Même nom que le fichier
  assets:
    - assets/images/logo.png  # ← logo.png comme ton fichier